### ISSUE TITLE
对于1px的数值不需要处理

### ISSUE THREAD

**Issue by reuwi** [qiuguorong/postcss-px-scale#6]

**Comment by qiuguorong** [comment]
原本提供了`/*no*/`注释以过滤不需要缩放的数值，但是想到转换的来源可能是已存在的css或第三方库，因此新增`ignoreValue`属性。如`1px`不需要处理缩放，则配置`ignoreValue: 1`或`ignoreValue: [1]`。请升级到`1.1.0`版本使用该属性

**Comment by reuwi** [comment]
@qiuguorong 🐂🍺,赶紧补一个🌟
